FIlter media files
BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final pull request #40
Opened 2024-03-20 16:37 UTC by angel23v

## Quick Info
Avoid to load other type of file, just accepting image format files

## Screenshot
![Screenshot from 2024-03-20 10-34-20](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final/assets/86389712/50ed0817-9d98-4621-93f8-5a53035f2445)

2024-03-20 16:49 UTC, MauricioNC approved these changes

2024-03-20 16:49 UTC, MauricioNC commented on app/views/posts/_form.html.erb
> +        <% else %>
Indent correctly this code

2024-03-20 17:53 UTC, MauricioNC requested changes

2024-03-20 17:53 UTC, MauricioNC commented on app/views/posts/_form.html.erb
> +        <% else %>
Indent correctly this code

2024-03-20 21:19 UTC, MauricioNC approved these changes

2024-03-21 00:31 UTC, juperameza approved these changes

2024-03-21 00:36 UTC, BlazeDex approved these changes

2024-03-21 00:37 UTC, merged