Add mobile styles to create post view
BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final pull request #51
Opened 2024-04-05 01:27 UTC by etormasa

# Description
add styles to new post form

## Screenshots

![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final/assets/106860103/0c108ead-dfb5-44a9-b36e-920ce6ff3cac)
![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final/assets/106860103/8fac54c4-b106-4f8a-8d54-aab6091bd24b)

2024-04-05 01:34 UTC, angel23v reviewed
sort alphabetically

2024-04-05 01:36 UTC, Zama15 requested changes
i add the class .form in my PR, lets see if we do not overwrite our changes

2024-04-05 01:36 UTC, Zama15 commented on app/assets/stylesheets/components/_form.scss
> +.form{
space between { and the class

2024-04-05 01:36 UTC, Zama15 commented on app/assets/stylesheets/components/_form.scss
> +.col_form{
space between { and the class

2024-04-05 01:37 UTC, angel23v commented on app/assets/stylesheets/components/_form.scss
sort alphabetically

2024-04-05 01:37 UTC, angel23v commented on app/assets/stylesheets/components/_buttons.scss
sort alphabetically

2024-04-05 01:37 UTC, angel23v commented on app/views/posts/_form.html.erb
Please indentation this file

2024-04-05 01:50 UTC, juperameza commented on app/assets/stylesheets/components/_buttons.scss
Aren't they already?

2024-04-05 01:53 UTC, juperameza requested changes
Shouldnt it be better to use a rich text box due for the post body?
Or is it intended to be something short and descriptive like a title per say

2024-04-05 01:53 UTC, juperameza commented on app/assets/stylesheets/components/_form.scss
> +    padding: 10px;
ORder alphabetically 
```suggestion
    background-color: $tertiary-color-light;
    border-radius: 10px;
    display: flex;
    flex-direction: row;
    height: 60%;
    margin: auto;
    padding: 10px;
    width: 90%;
```

2024-04-05 23:13 UTC, etormasa commented on app/assets/stylesheets/components/_form.scss
> +    padding: 10px;
done :)

2024-04-05 23:14 UTC, etormasa commented on app/assets/stylesheets/components/_form.scss
> +.form{
done :+1:

2024-04-05 23:14 UTC, etormasa commented on app/assets/stylesheets/components/_form.scss
> +.col_form{
done, and changed the class name :+1:

2024-04-05 23:14 UTC, etormasa commented on app/assets/stylesheets/components/_form.scss
done

2024-04-05 23:32 UTC, etormasa commented on app/views/posts/_form.html.erb
done

2024-04-06 00:52 UTC, angel23v approved these changes

2024-04-06 00:52 UTC, angel23v commented on app/assets/stylesheets/components/_buttons.scss
good eye mentor

2024-04-06 00:52 UTC, Zama15 approved these changes
LGTM

2024-04-06 00:53 UTC, juperameza approved these changes

2024-04-06 00:58 UTC, merged