Routines
BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final pull request #58
Opened 2024-04-09 02:08 UTC by angel23v

## Quick Info

Now you can create a routine, see details, edit and delete, this is just the basis to later be able to create series within each routine.

## Screenshots
General view
![index](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final/assets/86389712/c453d3b1-c297-43e1-b4be-d258fe0f1e77)
New Routine
![new](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final/assets/86389712/70e24d5a-195a-4821-9465-f8084823b17d)
Edit Routine
![edit](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final/assets/86389712/d45c253c-f89b-46aa-89de-152610c537f0)
Routine Details
![details](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final/assets/86389712/a96ccd14-0056-4a65-a278-fcbe10188391)

2024-04-09 02:45 UTC, MauricioNC requested changes

2024-04-09 02:45 UTC, MauricioNC commented on app/controllers/routines_controller.rb
> +    # @routines = current_user.routines.order(created_at: :desc)
Remove unnecessary comments

2024-04-09 02:47 UTC, juperameza requested changes

2024-04-09 02:47 UTC, juperameza commented on app/controllers/routines_controller.rb
> +    # @routines = current_user.routines.order(created_at: :desc)
Don't leave commented code

2024-04-10 16:46 UTC, juperameza requested changes

2024-04-10 16:46 UTC, juperameza commented on app/views/routines/show.html.erb
> +</div>
Why do the divs have empty class attributes 
Just delete them 
Also mind the usage of divs 
It makes your seo worse and isn't accessible

2024-04-10 18:32 UTC, MauricioNC approved these changes

2024-04-10 18:32 UTC, BlazeDex commented on app/controllers/routines_controller.rb
> +  def show
Change to def show;end

2024-04-10 18:32 UTC, BlazeDex commented on app/views/layouts/_footer.html.erb
>    <a href="">
Don't leave empty href. If you don't need it, delete it.

2024-04-10 18:32 UTC, BlazeDex commented on app/views/routines/index.html.erb
> +  <p>No se encontraron rutinas.</p>
Change to english. We need a consistent language.

2024-04-10 18:32 UTC, BlazeDex commented on app/views/routines/show.html.erb
> +    <strong>Usuario:</strong> <%= @routine.user.name %>
Same here.

2024-04-10 19:08 UTC, angel23v commented on app/views/routines/index.html.erb
> +  <p>No se encontraron rutinas.</p>
¡¡¡¡that's right!!!!!

2024-04-10 23:43 UTC, BlazeDex approved these changes

2024-04-12 00:19 UTC, juperameza approved these changes

2024-04-12 00:22 UTC, merged