Series view
BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final pull request #78
Opened 2024-04-26 02:36 UTC by etormasa

# Description

Implement views
Add js to make set green the div when checkbox is checked

## Screenshots

no spaces aligned
![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final/assets/106860103/036bc3da-c1db-44e1-8902-9f09d0b4eef4)

with spaces aligned 

![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final/assets/106860103/b0fda2e0-ca9e-493e-9add-bab1f79f3304)

2024-04-26 04:18 UTC, PudinDeveloper approved these changes
LGTM 🥥

2024-04-26 14:08 UTC, angel23v approved these changes

2024-04-26 16:59 UTC, MauricioNC approved these changes

2024-04-26 17:53 UTC, BlazeDex approved these changes

2024-04-26 17:55 UTC, BlazeDex commented
Just fix conflicts.

2024-04-26 19:16 UTC, juperameza requested changes

2024-04-26 19:16 UTC, juperameza commented on app/views/exercises/_exercises.html.erb
> +    <div class="checkbox-wrapper-44 miCheckbox">
Maybe change micheckbox to something more easy to understand when you see it 
What if there's another checkbox would it be yourcheckbox?
Remember to have good variable naming to have an easier time understanding your code

2024-04-26 19:18 UTC, juperameza requested changes

2024-04-26 19:18 UTC, juperameza commented on app/assets/stylesheets/pages/_routines.scss
> +}
Same here
Left part right part

2024-04-27 00:24 UTC, juperameza approved these changes

2024-04-27 00:25 UTC, merged