Create excersice menu mobile view
BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final pull request #89
Opened 2024-05-04 00:29 UTC by etormasa

# Description

Create menu with corresponding routes

## Screenshots

![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final/assets/106860103/e87f6e63-a7b5-41dd-b3de-fed08c0daf62)

2024-05-04 00:37 UTC, PudinDeveloper approved these changes
LGTM

2024-05-04 00:38 UTC, MauricioNC approved these changes

2024-05-04 02:31 UTC, Zama15 approved these changes
LGTM

2024-05-04 03:49 UTC, juperameza requested changes

2024-05-04 03:49 UTC, juperameza commented on app/controllers/selector_controller.rb
> +
Add a new line at the end of the file

2024-05-04 03:49 UTC, juperameza commented on app/controllers/selector_controller.rb
> +
aslo what is selector??? what is the purpose of this controller

2024-05-04 18:06 UTC, BlazeDex commented on app/controllers/selector_controller.rb
> +    end
Change to `def index; end`

2024-05-06 23:47 UTC, BlazeDex approved these changes

2024-05-07 05:45 UTC, angel23v approved these changes
Please don't forget to link the issue for every PR that you do

2024-05-07 06:29 UTC, juperameza approved these changes
Lgbt

2024-05-07 23:35 UTC, merged